var num1;
var num2;
num1 = 4;
num2 = 4;
console.log("Addition of ", num1, "\+", num2, "\=", num1 + num2);
num1 = 2;
num2 = 4;
console.log("Multiplication of ", num1, "x", num2, "\=", num1 * num2);
num1 = 16;
num2 = 8;
console.log("Substraction of ", num1, "\-", num2, "\=", num1 - num2);
num1 = 64;
num2 = 8;
console.log("Division of ", num1, "\/", num2, "\=", num1 / num2);
